export const globalHyperlinks = {
  basic: [
    { word: "ニセ", href: "https://www.npa.go.jp/bureau/safetylife/sos47/new-topics/241218/02.html" },
    { word: "テクスチャ", href: "https://www.token.co.jp/estate/useful/archipedia/word.php?jid=00016&wid=00266&wdid=01" },
    { word: "通信", href: "https://www.soumu.go.jp/johotsusintokei/whitepaper/ja/s54/html/s54a01020202.html" },
    { word: "飲み会", href: "https://note.com/wakusei2nduno/n/nd8f850fbde4d" },
    { word: "つまらなさ", href: "https://x.com/haraajukku/status/1853686504809443769" },
    { word: "ジョッキ", href: "https://ja.wikipedia.org/wiki/%E3%83%93%E3%83%BC%E3%83%AB%E3%82%B8%E3%83%A7%E3%83%83%E3%82%AD#/media/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:BIER_IM_EG.jpg" },
    { word: "陽気", href: "https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1363737843" },
    { word: "涙", href: "https://ja.wikipedia.org/wiki/%E6%B6%99" },
    { word: "武勇伝", href: "https://sayapea.exblog.jp/439216/" },
    { word: "スピリッツ", href: "https://www.suntory.co.jp/wnb/guide/spirits/01/" },
    { word: "解散", href: "https://youtu.be/CrVR1YEQP2k?si=nIlH2v1rFqaTHuUM&t=98" },
    { word: "張子", href: "https://goodjobstore.jp/collections/%E3%81%AF%E3%82%8A%E3%81%93" },
    { word: "空洞", href: "https://youtu.be/mKUhq7SYouA?si=5MkAMTYIA7JC5-3i" },
    { word: "内包", href: "https://www.weblio.jp/content/%E5%86%85%E5%8C%85" },
    { word: "型", href: "https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q13247187703" },
    { word: "青菜炒め", href: "https://misenyaba.owst.jp/foods" },
    { word: "循環", href: "https://www.rd.ntt/se/media/article/0044.html" },
    { word: "フィクション", href: "https://youtu.be/kmT_aQh2TwQ?si=BBNZBBF82CqZy3TJ" },
    { word: "ノンフィクション", href: "http://www.insecam.org/" },
    { word: "露悪", href: "https://dic.nicovideo.jp/a/%E9%9C%B2%E6%82%AA" },
    { word: "俯瞰", href: "https://www.google.com/maps" },
    { word: "酩酊", href: "https://www.iwate.med.or.jp/hanamaki/P-9.html" },
    { word: "世迷言", href: "https://www.uta-net.com/song/54556/" },
    { word: "(｀･ω･´)", href: "https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1357121248" },
    { word: "ハラスメント", href: "https://ja.wikipedia.org/wiki/%E5%AB%8C%E3%81%8C%E3%82%89%E3%81%9B" },
    { word: "暖房の風が直接当たって唇が乾いて", href: "https://www.yuskin.co.jp/skincare/skincare_03/" },
    { word: "テレビに逐一悪口", href: "https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q14168380004" },
    { word: "“飲みュニケーション”", href: "https://ja.wikipedia.org/wiki/%E9%A3%B2%E3%81%BF%E3%83%8B%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3" },
    { word: "地獄", href: "https://daishinowa.jp/column/shingon/98" },
    { word: "麻雀", href: "https://mahjongsoul.com/" },
    { word: "ヘルメット", href: "http://www.kawaharahelmet.com/shouhinjyouhoumenu.htm" },
    { word: "苅田市", href: "https://maps.app.goo.gl/nGbbN3vhLoVBcpsY8" },
    { word: "竹瓦温泉", href: "https://www.takegawara-onsen.com/" },
    { word: "パン", href: "https://www.panpedia.jp/Recipedisp/Panlist" },
    { word: "ラミネート", href: "http://www.jol-net.co.jp/info/lumi_p.html" },
    { word: "15分", href: "https://www.timer.net/ja/15%E5%88%86.html" },
    { word: "かまど地獄", href: "https://www.beppu-jigoku.com/kamado/" },
    { word: "博多華丸・大吉", href: "https://profile.yoshimoto.co.jp/talent/detail?id=213" },
    { word: "怒られたくない", href: "https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q13326066268" },
    { word: "鬼山地獄", href: "https://mouthplustwo.me/" },
    { word: "目［mé］", href: "https://mouthplustwo.me/" },
    { word: "ロイヤルホスト", href: "https://youtu.be/Z7-RDg4KL1g?si=UfSGtUeHQkReJ0Hn" },
    { word: "高等温泉", href: "https://note.com/traveling_hi/n/n98ed47f70d64" },
    { word: "竹瓦温泉", href: "https://www.takegawara-onsen.com/" },
    { word: "にちりんシーガイア", href: "https://www2s.biglobe.ne.jp/~t_aoyagi/train/seagaia.htm" },
    { word: "イメージ", href: "https://keyword.japancreativity.jp/basics/image/" },
    { word: "寺の標語", href: "https://www.bdk.or.jp/kagayake2018/publication.html" },
    { word: "うんこ座り", href: "https://iwata-akatombo.com/blog/?p=3619" },
    { word: "風の谷のナウシカ", href: "https://www.ghibli.jp/works/nausicaa/" },
    { word: "小池百合子", href: "https://www.yuriko.or.jp/" },
    { word: "松本人志", href: "https://www.shochiku.co.jp/wp-content/uploads/1901/08/c04660.jpg" },
    { word: "知多", href: "https://www.suntory.co.jp/whisky/chita/" },
    { word: "むっきーちゃん", href: "https://youtu.be/Ac_5sBWw8AA?si=DxupXNGOQ6xjoMHV" },
    { word: "鳥貴族", href: "https://torikizoku.co.jp/" },
    { word: "サラリーマン", href: "https://www.reddit.com/r/AskAJapanese/comments/1lxvg6i/what_exactly_is_a_salaryman/?tl=ja" },
    { word: "IAMAS", href: "https://www.iamas.ac.jp/" },
    { word: "秋の隕石", href: "https://autumnmeteorite.jp/ja" },
    { word: "COCOON（2022 ver）", href: "https://youtu.be/8EsDTlYlQsE?si=XazgHs-2G_dUNFsP" },
    { word: "マームとジプシー", href: "http://mum-gypsy.com/" },
    { word: "戦争", href: "https://ja.wikipedia.org/wiki/%E6%88%A6%E4%BA%89" },
    { word: "アル・リサーラ", href: "http://islamicff.com/" },
    { word: "リリーフランキー", href: "https://www2.nhk.or.jp/archives/articles/?id=D0009071481_00000" },
    { word: "タモリ", href: "https://www2.nhk.or.jp/archives/articles/?id=D0009070272_00000" },
    { word: "いとうせいこう", href: "https://www2.nhk.or.jp/archives/articles/?id=D0009071069_00000" },
    { word: "みうらじゅん", href: "https://www2.nhk.or.jp/archives/articles/?id=D0009071983_00000" },
    { word: "みうらじゅん賞", href: "https://ja.wikipedia.org/wiki/Category:%E3%81%BF%E3%81%86%E3%82%89%E3%81%98%E3%82%85%E3%82%93%E8%B3%9E%E5%8F%97%E8%B3%9E%E8%80%85" },
    { word: "河村たかし", href: "https://www.pref.aichi.jp/uploaded/life/262858_902508_misc.pdf" },
    { word: "中道改革連合", href: "https://craj.jp/" },
    { word: "衆議院選挙", href: "https://www.soumu.go.jp/senkyo/senkyo_s/naruhodo/naruhodo03.html#chapter1" },
    { word: "ゼッテリア", href: "https://www.zetteria.jp/" },
    { word: "小倉駅", href: "https://maps.app.goo.gl/oD8RuTrrco8p32QS7" },
    { word: "自民党", href: "https://www.jimin.jp/" },
    { word: "radiko", href: "https://radiko.jp/" },
    { word: "行橋", href: "https://w.atwiki.jp/medakabox/pages/37.html" },
    { word: "サイゼリヤ", href: "https://www.saizeriya.co.jp/" },
    { word: "スリーコインズ", href: "https://www.palcloset.jp/3coins/" },
    { word: "別府", href: "https://www.city.beppu.oita.jp/" },
    { word: "新年会", href: "https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1099756270" },
    { word: "忘年会", href: "https://kurahiro.tepco.co.jp/life/32963/index.html" },
    { word: "福沢諭吉", href: "https://fukuzawakyukyo.com/access/" },
  ],
  musicLinks: [

  ]
};